apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: manual
