apiVersion: v1
kind: Pod
metadata:
  name: "mongodb"
  namespace: default
  labels:
    app: "mongodb"
spec:
  containers:
  - name: mongodb
    image: mongo
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 27017
      protocol: TCP
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb
  restartPolicy: Always
