apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  progressDeadlineSeconds: 100
  selector:
    matchLabels:
      app: kubia
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: nodejs
        image: luksa/kubia:v3
        livenessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
