apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-03-06T21:33:08Z"
  labels:
    run: loadergenerator
  name: loadergenerator
  namespace: default
  resourceVersion: "842"
  uid: 99ae6ad2-f2f8-4cf5-af00-4eadce3975e7
spec:
  containers:
  - args:
    - sh
    - -c
    - while true; do wget -O - -q http://kubia.default; done
    image: busybox
    imagePullPolicy: Always
    name: loadergenerator
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zxq4s
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-zxq4s
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-03-06T21:33:08Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-03-06T21:33:29Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-03-06T21:33:29Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-03-06T21:33:08Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0e9cf137a42dcfa92867fed156192cd728772c1ad432ffd20d14157805bc1d14
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:478209e7be50e5f5c9fd47a6a71d43c119dd44c393160e49dc4bb86f99a439de
    lastState: {}
    name: loadergenerator
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-03-06T21:33:29Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.0.9
  podIPs:
  - ip: 10.244.0.9
  qosClass: BestEffort
  startTime: "2024-03-06T21:33:08Z"
