apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: default
  labels:
    app: curl
spec:
  containers:
  - name: ambassador
    image: luksa/kubectl-proxy
  - name: curl
    image: curlimages/curl
    command:
    - sleep
    - "999999"
